# Generated by Django 5.1.2 on 2024-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='pin',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
